"""Initial models

Revision ID: c7f5825def9e
Revises: 
Create Date: 2026-06-17 22:32:52.123411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7f5825def9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carbon_activities', sa.Column('emissions_kg', sa.Float(), nullable=True))
    op.add_column('carbon_activities', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('carbon_activities', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('carbon_activities', 'activity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('carbon_activities', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_carbon_activities_activity_date'), table_name='carbon_activities')
    op.drop_index(op.f('ix_carbon_activities_user_id'), table_name='carbon_activities')
    op.drop_constraint(op.f('carbon_activities_user_id_fkey'), 'carbon_activities', type_='foreignkey')
    op.create_foreign_key(None, 'carbon_activities', 'users', ['user_id'], ['id'])
    op.drop_column('carbon_activities', 'unit')
    op.drop_column('carbon_activities', 'is_local')
    op.drop_column('carbon_activities', 'quantity')
    op.drop_column('carbon_activities', 'is_organic')
    op.drop_column('carbon_activities', 'created_at')
    op.drop_column('carbon_activities', 'meal_type')
    op.drop_column('carbon_activities', 'product_name')
    op.drop_column('carbon_activities', 'activity_metadata')
    op.drop_column('carbon_activities', 'carbon_emission')
    op.drop_column('carbon_activities', 'price')
    op.drop_column('carbon_activities', 'category')
    op.drop_column('carbon_activities', 'updated_at')
    op.drop_column('carbon_activities', 'distance')
    op.drop_column('carbon_activities', 'vehicle_type')
    op.drop_column('carbon_activities', 'activity_date')
    op.drop_column('carbon_activities', 'location')
    op.drop_column('carbon_activities', 'brand')
    op.drop_column('carbon_activities', 'source')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_column('users', 'country')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'auth_id')
    op.drop_column('users', 'name')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'points')
    op.drop_column('users', 'onboarded')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'total_co2_kg')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'streak_last_date')
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'role')
    op.drop_column('users', 'location')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'carbon_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('carbon_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'admin', 'premium', name='userrole'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('streak_last_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('total_co2_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('onboarded', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('streak_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('auth_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'full_name')
    op.add_column('carbon_activities', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('activity_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('carbon_activities', sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('carbon_activities', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('carbon_emission', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('carbon_activities', sa.Column('activity_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('meal_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('is_organic', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('carbon_activities', sa.Column('is_local', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('carbon_activities', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'carbon_activities', type_='foreignkey')
    op.create_foreign_key(op.f('carbon_activities_user_id_fkey'), 'carbon_activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_carbon_activities_user_id'), 'carbon_activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_carbon_activities_activity_date'), 'carbon_activities', ['activity_date'], unique=False)
    op.alter_column('carbon_activities', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('carbon_activities', 'activity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('carbon_activities', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('carbon_activities', 'date')
    op.drop_column('carbon_activities', 'emissions_kg')
    # ### end Alembic commands ###
