"""add_target_value_to_goals

Revision ID: fbb98bc6dec0
Revises: c7f5825def9e
Create Date: 2026-06-21 01:35:30.636227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb98bc6dec0'
down_revision: Union[str, Sequence[str], None] = 'c7f5825def9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add columns that are definitely missing
    op.add_column('goals', sa.Column('target_value', sa.Float(), nullable=True))
    op.add_column('goals', sa.Column('current_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    op.drop_table('community_posts')
    # ### end Alembic commands ###
